### ISSUE TITLE
Differences from other overlay networks

### ISSUE THREAD

**Issue by ChronosX88** [The-Garlic-Network/The-Garlic-Network#1]
How is your network SPECIFICALLY different from others (e.g. Yggdrasil)?

**Comment by mrrva** [comment]
Hello. Thank you for your question! 
I can't tell you the difference between my network and Yggdrasil (but I can compare my network with TOR because I know how it works in details) because I don't know Yggdrasil's details of organizations. But I can show you a list of positions which I try to stick:

-   Max speed of work - I trying to create a solution which will be work with high speed (architecture of the project proves it).
-   The project has own protocol.
-   It's simple to use - If you saw source code of the user library you could notice that it has just 10 functions. Any person with any level of knowledge can make own solution based on my network.

You should to know: I've opened a discussion about project and concept.

_P.S. It's hard to compare projects when one of them has a community and was created a long time ago and the other one has been created month ago._
